/** Fictional, inspectable work for the public sample. Never customer data. */
export const teammates = [
    { id: "kit", name: "Kit", role: "Launch producer", icon: "/teammates/loop-v1.png", app: "Launch studio", promise: "Give me the launch date. I’ll keep everything moving toward it.", waiting: "2 assets ready · 1 decision", job: "Keep our launch moving. Maintain the brief, prepare assets, check dependencies, and bring publishing decisions to Priya.", learned: "Lead with the customer’s problem. No superlatives. Never reuse the ‘all-in-one’ positioning Priya rejected. Customer quotes and publishing need Priya’s approval.", ask: "Where are we on Thursday’s launch?", reply: "Two assets are ready for review. The demo still shows the old onboarding: I’ve marked the affected shots and revised the script. Harbor’s customer story is drafted, but logo permission is missing. Nothing has been published.", items: [
        { title: "Launch announcement", status: "Ready for review", owner: "Priya", detail: "Your first import, with someone beside you.\n\nAcme now walks your team through mapping columns, checking a sample, and resolving errors before the full import. Start with one useful result, then bring the rest of your work across.", source: "Brief v3 · Product review, Sept 22", action: "Mark reviewed" },
        { title: "Product demo · script v4", status: "3 shots to update", owner: "Dev", detail: "00:08 — Replace the old upload dialog.\n00:19 — Show column mapping with the Harbor sample.\n00:31 — End on the successful import, not the settings screen.\n\nVoiceover: ‘Check a sample first. Fix what needs attention. Then bring the whole file in.’", source: "Product walkthrough · Sept 23", action: "Assign update to Dev" },
        { title: "Harbor customer story", status: "Permission missing", owner: "Priya", detail: "The story is ready for internal review. Harbor has not approved use of its name or logo.\n\nFallback: publish the walkthrough without customer attribution. Ask Priya which version to prepare.", source: "Customer permission log · No approval recorded", action: "Prepare anonymous version" },
    ] },
    { id: "remy", name: "Remy", role: "Sales follow-through", icon: "/teammates/pleat-v1.png", app: "Deal desk", promise: "Every promising conversation gets a next step.", waiting: "1 buyer waiting on us", job: "Track buyer commitments, prepare relevant follow-ups, and keep every opportunity’s next step current. Ask before sending or changing pricing.", learned: "Anita is Northstar’s buyer; Raj is the technical evaluator. Check recent colleague conversations before proposing another follow-up. Only use approved security documents.", ask: "Who’s waiting on us?", reply: "Northstar asked for our security overview on Tuesday. I’ve prepared a reply with the approved document; their procurement deadline is Friday. I’m holding the Cedar follow-up because Priya spoke with them yesterday. Harbor has signed: June has the promised first-import outcome.", items: [
        { title: "Northstar · Security overview", status: "Waiting for us", owner: "Priya", detail: "To: Anita\n\nHi Anita — following up on Tuesday’s call, here’s the approved security overview for your procurement review. Raj’s deployment questions are covered in section 3. Let us know what else your team needs ahead of Friday.\n\nAttachment: Security overview — approved September edition", source: "Tuesday demo notes · Anita’s procurement email", action: "Mark draft reviewed" },
        { title: "Cedar · Evaluation", status: "Follow-up held", owner: "Priya", detail: "Priya spoke with Cedar yesterday. They are testing with their operations team on Thursday.\n\nNext step: check for their result on Friday. A reminder today would duplicate Priya’s conversation.", source: "Priya’s account note · Sept 22", action: "Confirm Friday check-in" },
        { title: "Harbor · Signed", status: "Handed to June", owner: "June", detail: "Purchased for weekly customer imports. Success means importing a validated customer file.\n\nJune has the call notes, sample requirements, and customer owner. No custom integration was promised.", source: "Signed scope · Sales handoff", action: "Acknowledge handoff" },
    ] },
    { id: "june", name: "June", role: "Customer onboarding", icon: "/teammates/frame-v1.png", app: "Customer launchpad", promise: "I’ll stay until each customer gets their first useful result.", waiting: "1 import needs help", job: "Tailor each onboarding plan to the sold outcome. Track inputs, prepare help, and escalate blockers with evidence. Ask before changing scope or delivery commitments.", learned: "Setup is not success. Harbor needs a validated customer import. Hold training reminders while a blocking import error remains unresolved.", ask: "Is Harbor ready for training?", reply: "Not yet. Setup is complete, but their first import failed because the date column uses mixed formats. I’ve prepared a corrected sample and an escalation for Dev. The training reminder is held until the import works.", items: [
        { title: "Harbor · First customer import", status: "Blocked", owner: "Dev", detail: "Goal: one validated customer import.\nCompleted: account access, source file received, columns mapped.\nBlocked: dates mix DD/MM/YYYY and YYYY-MM-DD.\n\nPrepared: a normalized 10-row sample for Dev to validate. Keep the original file unchanged.", source: "Import error log · Harbor sample, Sept 23", action: "Assign diagnosis to Dev" },
        { title: "Harbor · Training session", status: "Reminder held", owner: "Priya", detail: "Training depends on a successful sample import. Sending the reminder now would ask the customer to prepare for a workflow they cannot yet use.\n\nNext: confirm Dev’s validation, then agree a training time with the customer.", source: "Onboarding plan · Import dependency", action: "Confirm hold" },
        { title: "Cedar · Onboarding preparation", status: "Plan drafted", owner: "June", detail: "Cedar is still evaluating. The draft plan is internal until the deal closes.\n\nFirst outcome: one weekly operations report. Inputs needed: example report, source export, and the customer’s report owner.", source: "Remy’s evaluation notes", action: "Review draft plan" },
    ] },
    { id: "scout", name: "Scout", role: "Customer researcher", icon: "/teammates/extended/gem.png", app: "Evidence notebook", promise: "Keep important questions connected to evidence.", waiting: "1 finding to challenge", job: "Investigate bounded customer questions. Keep source excerpts, competing explanations, and uncertainty visible. Revisit findings when evidence changes.", learned: "Repeated comments are signals, not proof. Separate setup effort from price objections. Preserve counterexamples and show the sample size with every conclusion.", ask: "Why are our trials stalling?", reply: "In this sample of five lost-deal conversations, three mention setup effort. One names budget and one lacks an internal owner. This does not establish the main cause across all trials. June’s import blockers suggest a guided-onboarding experiment worth testing.", items: [
        { title: "Question · Why do trials stall?", status: "Working hypothesis", owner: "Scout", detail: "Setup effort appears in 3 of 5 reviewed conversations. Budget appears in 1; lack of an internal owner appears in 1.\n\nLimit: small, selected sample of lost deals. We have not compared successful trials.\n\nNext: compare five converted trials before treating this as a broader pattern.", source: "Research sample · Five fictional interview notes", action: "Request converted-trial comparison" },
        { title: "Evidence · Setup effort", status: "3 source excerpts", owner: "Scout", detail: "Northstar: ‘We need someone to walk us through the first file.’\nBirch: ‘We ran out of time mapping our export.’\nElm: ‘The import errors left us unsure what to fix.’\n\nCounterexample — Pine: ‘The workflow fits; this quarter’s budget doesn’t.’", source: "Interview notes N1, B2, E3, P4 · Sample data", action: "Flag selection bias" },
        { title: "Experiment · Guided first import", status: "Proposed", owner: "Priya", detail: "Offer guided first-import support to the next five eligible trials. Record completion, time to first result, and support effort.\n\nCompare with the previous cohort cautiously: account size and source complexity may differ. Priya decides whether to run the experiment.", source: "June’s blocker report + lost-deal review", action: "Queue for Priya’s review" },
    ] },
];
export function teammateFor(id: string) { return teammates.find(person => person.id === id) ?? teammates[0]; }
