/** The cast, and how each one is cropped into a small mark.
 *
 *  `face` is where the eyes are, as a fraction of the portrait: every
 *  character in this cast has two near-black pupils ringed by ivory, so the
 *  centroid of that pair is the face. The mark does not crop to it — cropping
 *  at 170% cuts legs and arms off at every size — so the tile contains the
 *  whole character and the measurement is kept for anything that wants to aim
 *  at a face.
 *
 *  Generated by `scripts/cast-portraits.py`; edit there, not here. */

export const CHARACTERS = [
    "arch",
    "bean",
    "bloom",
    "bolt",
    "cloud",
    "coil",
    "cube",
    "frame",
    "gem",
    "grid",
    "kite",
    "knot",
    "loop",
    "moon",
    "peak",
    "pleat",
    "prism",
    "ring",
    "spark",
    "spool",
    "sprout",
    "stack",
    "wave",
    "wedge",
] as const;
export type CharacterName = typeof CHARACTERS[number];

export const CAST: Record<CharacterName, { face: [number, number] }> = {
    arch: { face: [0.511, 0.25] },
    bean: { face: [0.464, 0.285] },
    bloom: { face: [0.553, 0.401] },
    bolt: { face: [0.498, 0.315] },
    cloud: { face: [0.543, 0.369] },
    coil: { face: [0.504, 0.203] },
    cube: { face: [0.563, 0.353] },
    frame: { face: [0.521, 0.297] },
    gem: { face: [0.486, 0.355] },
    grid: { face: [0.526, 0.202] },
    kite: { face: [0.527, 0.353] },
    knot: { face: [0.539, 0.327] },
    loop: { face: [0.518, 0.417] },
    moon: { face: [0.498, 0.393] },
    peak: { face: [0.501, 0.466] },
    pleat: { face: [0.495, 0.288] },
    prism: { face: [0.571, 0.348] },
    ring: { face: [0.527, 0.183] },
    spark: { face: [0.529, 0.382] },
    spool: { face: [0.535, 0.257] },
    sprout: { face: [0.521, 0.398] },
    stack: { face: [0.548, 0.223] },
    wave: { face: [0.566, 0.221] },
    wedge: { face: [0.617, 0.348] },
};

/** Which character a pod wears when it has not been given a picture.
 *
 *  A different multiplier from the hue hash in `mark.tsx` on purpose: derived
 *  from the same string, the two would otherwise march in step and every Bloom
 *  would share a tint.
 *
 *  Here rather than beside the component that draws it, because it is a pure
 *  rule about a string and the test runner cannot load a `.tsx` at all — the
 *  same reason `auth-state.ts` sits apart from `session.tsx`. The component
 *  re-exports it, so nothing importing it from there had to change.
 */
export function characterForSeed(seed: string): CharacterName {
    let hash = 7;
    for (let index = 0; index < seed.length; index += 1) {
        hash = (hash * 131 + seed.charCodeAt(index)) % 1000003;
    }
    return CHARACTERS[hash % CHARACTERS.length];
}
