/**
 * Lemma's interface icon vocabulary.
 *
 * Product UI imports icons from this module instead of depending on a vendor's
 * naming scheme. Phosphor is the single glyph family underneath the vocabulary.
 * Brand marks, user-provided images, illustrations, diagrams, and data
 * visualizations intentionally live outside this module.
 *
 * Some exported names preserve the old call-site vocabulary so the visual
 * migration can stay reviewable. The mapping here is the canonical decision:
 * one UI concept resolves to one Phosphor glyph everywhere in the product.
 */

export type {
    Icon as LemmaIcon,
    IconProps as LemmaIconProps,
    IconWeight as LemmaIconWeight,
} from '@phosphor-icons/react';

// Names shared by Lucide and Phosphor.
export {
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpRight,
    BookOpen,
    Briefcase,
    Bug,
    Calendar,
    Check,
    CheckCircle,
    CheckSquare,
    Circle,
    Clock,
    Code,
    Copy,
    Cpu,
    Database,
    Download,
    Eye,
    File,
    FileArchive,
    FileAudio,
    FileCode,
    FileImage,
    FileText,
    FileVideo,
    Files,
    Flag,
    Flame,
    Folder,
    FolderOpen,
    FolderPlus,
    Footprints,
    GitBranch,
    GitPullRequest,
    Handshake,
    Headphones,
    Image,
    Info,
    Lightbulb,
    Link,
    List,
    Lock,
    ListChecks,
    Moon,
    Minus,
    Newspaper,
    Package,
    Pause,
    PauseCircle,
    Pencil,
    Play,
    PlayCircle,
    Plug,
    Plus,
    Presentation,
    Receipt,
    Repeat,
    ShieldCheck,
    Square,
    Sun,
    Table,
    Terminal,
    Timer,
    Upload,
    User,
    UserCheck,
    UserPlus,
    Users,
    Wrench,
    X,
    XCircle,
} from '@phosphor-icons/react/ssr';

// Stable Lemma vocabulary mapped to the closest Phosphor concept.
export {
    WarningCircle as AlertCircle,
    Warning as AlertTriangle,
    Bell,
    CurrencyDollar as BadgeDollarSign,
    ChartBar as BarChart3,
    BookOpenText as BookA,
    Robot as Bot,
    Cube as Box,
    CubeTransparent as Boxes,
    BracketsCurly as Braces,
    Buildings as Building2,
    CalendarDots as CalendarClock,
    CalendarBlank as CalendarDays,
    CheckCircle as CheckCircle2,
    CaretDown as ChevronDown,
    CaretLeft as ChevronLeft,
    CaretRight as ChevronRight,
    CaretUp as ChevronUp,
    // Switching between peers, not opening a menu. A lone down-caret says "there
    // is more below this"; the pair says "there are others, and you can move to
    // one" — which is the whole promise a pod switcher makes.
    CaretUpDown as ChevronsUpDown,
    Question as CircleHelp,
    ClipboardText as ClipboardList,
    Clock as Clock3,
    CodeBlock as Code2,
    Gear as Cog,
    AddressBook as Contact2,
    CopySimple as CopyCheck,
    PencilSimple as Edit,
    PencilSimple as Edit2,
    ArrowSquareOut as ExternalLink,
    FileCode as FileCode2,
    File as FileIcon,
    FileJs as FileJson,
    FileArrowUp as FileOutput,
    FileText as FilePenLine,
    FileMagnifyingGlass as FileSearch,
    FileCsv as FileSpreadsheet,
    Files as FileStack,
    Funnel as Filter,
    Function as FunctionSquare,
    GithubLogo as Github,
    Globe as Globe2,
    DotsSixVertical as GripVertical,
    // A column's data type, in the width a bounded grid header can spare. The
    // three below exist for that vocabulary: a number, a word, a label.
    Hash,
    ClockCounterClockwise as History,
    House as Home,
    ImageSquare as ImagePlus,
    Tray as Inbox,
    Key as KeyRound,
    StackSimple as Layers3,
    GridFour as LayoutDashboard,
    SquaresFour as LayoutGrid,
    Lifebuoy as LifeBuoy,
    LinkSimple as Link2,
    ListChecks as ListTodo,
    SpinnerGap as Loader2,
    LockKey as LockKeyhole,
    SignOut as LogOut,
    Envelope as Mail,
    MapTrifold as Map,
    ArrowsOut as Maximize2,
    List as Menu,
    ChatCircle as MessageCircle,
    ChatCircleDots as MessageCircleQuestion,
    Chat as MessageSquare,
    ChatCenteredDots as MessageSquarePlus,
    Chats as MessagesSquare,
    Microphone as Mic,
    ArrowsIn as Minimize2,
    DotsThree as MoreHorizontal,
    DotsThreeVertical as MoreVertical,
    MusicNote as Music,
    NotePencil as NotebookPen,
    Package as PackageOpen,
    SidebarSimple as PanelLeftClose,
    Sidebar as PanelLeftOpen,
    SidebarSimple as PanelRightClose,
    Layout as PanelsTopLeft,
    PushPin as Pin,
    Printer,
    PuzzlePiece as Puzzle,
    Receipt as ReceiptText,
    ArrowsClockwise as RefreshCw,
    ArrowCounterClockwise as RotateCcw,
    FloppyDisk as Save,
    Scales as Scale,
    MagnifyingGlass as Search,
    PaperPlaneTilt as Send,
    // Settings is sliders, not a gear — the same glyph the ProductIcon registry
    // resolves `settings` to. Aliasing it here rather than at each call site is
    // what makes that true everywhere: pod settings in the account menu, org
    // settings, a flow step's config, and Local settings all read from this one
    // line. `Cog` keeps the gear for the places that mean machinery — a system
    // actor, an operations category — which is a different idea from settings.
    SlidersHorizontal as Settings,
    SlidersHorizontal as Settings2,
    ShareNetwork as Share2,
    ShieldWarning as ShieldAlert,
    DeviceMobile as Smartphone,
    Sparkle as Sparkles,
    TerminalWindow as SquareTerminal,
    Table as Table2,
    Tag,
    TerminalWindow as TerminalSquare,
    TextAa as TextT,
    Trash as Trash2,
    UserCircle as UserRound,
    UsersThree as UsersRound,
    SpeakerHigh as Volume2,
    MagicWand as Wand2,
    TreeStructure as Waypoints,
    WebhooksLogo as Webhook,
    FlowArrow as Workflow,
    Lightning as Zap,
} from '@phosphor-icons/react/ssr';

// Brand glyphs used as icons may be exported here; full logos remain assets.
// The social marks below name share destinations, where a generic glyph would
// leave people guessing which button posts where.
export {
    DiscordLogo,
    GithubLogo,
    LinkedinLogo,
    RedditLogo,
    TelegramLogo,
    WhatsappLogo,
    XLogo,
} from '@phosphor-icons/react/ssr';

// Product/resource identity glyphs used by the semantic ProductIcon registry.
// These are chosen to sit at one optical weight: a nav that stacks them in a
// column shows up any glyph carrying more ink than its neighbours, so the
// lightest member of each concept family wins over the most literal one.
export {
    AppWindow,
    ChatTeardrop,
    Desktop as Monitor,
    Cube,
    FlowArrow,
    FolderSimple,
    MagicWand,
    Shield,
    SlidersHorizontal,
    Tray,
} from '@phosphor-icons/react/ssr';
