"""Identity of the OpenAPI spec this SDK was generated from.

GENERATED by ``scripts/generate_openapi_client.sh`` — do not edit by hand.

``API_VERSION`` mirrors the backend ``app.version.API_VERSION`` (the
``info.version`` of the spec the client was built against). ``SPEC_SHA256`` is
the SHA-256 of the bundled ``openapi_spec.json`` and acts as a precise
fingerprint of the schema shape. The ``lemma`` CLI reads these via
``lemma --version`` / ``lemma doctor`` to detect drift between the installed
SDK and the server it is talking to.
"""

from __future__ import annotations

API_VERSION = "0.8.0"
SPEC_SHA256 = "13eb52ffe93bef2c38893dcbb143a69ac3567445988f3a151f4596e5e038b648"
